services:
  - type: web
    name: movie-search-n8n-app
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python main.py
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright