services:
  - type: web
    name: movie-search-n8n-app
    env: python
    runtime: python-3.11.6
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && playwright install chromium
    startCommand: python main.py
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PYTHON_VERSION
        value: 3.11.6